# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismic_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seismicevent',
            name='fac',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mo',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mo_auth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mpp',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mpr',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mrr',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mrt',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mtp',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mtt',
            field=models.DecimalField(decimal_places='20', max_digits='20', null=True),
        ),
    ]
