# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismic_events', '0003_auto_20170528_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seismicevent',
            name='depth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='fac',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='lon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mo_auth',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mpp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mpr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mrr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mrt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mtp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mtt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='mw',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='q',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='q_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='q_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='s',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='smajax',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='sminax',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='strike',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='unc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seismicevent',
            name='unc_1',
            field=models.CharField(max_length=20),
        ),
    ]
